### ISSUE TITLE
안녕하세요 과제2 관련해서 질문사항이 있어 질문드립니다!

### ISSUE THREAD

**Issue by vhehfhvl** [snuwebprogramming/snu-chat#1]
1. 작성해주신 스켈레톤 코드를 보면 회원가입란이 있던데 이와 별도로 로그인 기능을 만들어야하는건지 궁금합니다!(회원가입할 때 서버에 요청하는 url이 /login이라고 돼있던데 별도로 로그인 기능을 만들지는 않아도 되는건가요?)
2. 만약 로그인 버튼을 만들지는 않고 회원가입 기능을 이용해서 로그인을 하는거라면 기 생성한 동일한 아이디로 회원가입을 했을 때 로그인이 제대로 되지 않고 undefined라고 뜨는 것 같습니다.(서버쪽 코드관련한 이슈같아서 질문 드립니다ㅜ)
3. 로그인 이력이 있을시 자동 로그인을 한다고 돼있는데 그냥 로컬스토레지 정보를 이용해서 브라우저 다시켰을 때 로그인이 돼있으면 되는건가요?(스켈레톤에 이미 구현돼있는 것 같은데 구현 기능 목록에 있어서 질문드립니다)
4. 마찬가지로 메세지 입력했을 때 채팅모드 다시 가져오는 것도 스켈레톤에 이미 구현돼있는 것 같은데 더 구현할 필요가 없는건가요?
5. 기능에서 로그인 완료시 방 목록에 있는 join버튼 활성화라고 돼있는데, 이 말의 뜻이 로그인을 하지 않으면 채팅을 못치는 것 뿐만이 아니라 아예 채팅방에 들어가서 채팅내역 자체를 볼 수 없게 만들어야한다는 뜻인지 궁금합니다.
6. 마지막으로 추가기능에 오프라인 모드에서 적절한 에러핸들링이라고 돼있는데 혹시 무엇을 의미하는지 좀 더 구체적으로 알 수 있을까요?

**Comment by realcom** [comment]
1. 현재 로그인은 굉장히 단순한 시스템으로 되어있습니다. /register로 얻은 키로 로그인 감지하시고, 추구 별도 로그인 request는 보내실 필요 없습니다.


2. 1로 답변이 된듯 합니다.


3. 네.


4. 네. 하지만 별도의 커스터마이징이 필요할 겁니다.(채팅 시간 등등)


5. 방 기능이 좀 애매하게 구현되어 있는데 수정후 내일 다시 알려드릴 예정입니다.


6. 오프라인 시, 오프라인이라고 명시 + 비활성화, 온라인으로 전환시 기능 재개 하면됩니다.

**Comment by realcom** [comment]
로그인 관련하여 수정되었습니다. 리드미를 참고해주세요.
