### ISSUE TITLE
안녕하세요 chatting project 관련 질문 드립니다.!

### ISSUE THREAD

**Issue by heeedol** [snuwebprogramming/snu-chat#2]
1. 제출 기한이 6월 14일까지 맞나요? 깃헙에는 6월 10일 이라고 써져있습니다. 
2. 유저 리스트에는 현재 로그인 되어 있는 유저의 이름을 띄워야 하나요?

**Comment by realcom** [comment]
1. 6월 14일입니다.
2. 채팅 방 유저리스트 관련하여 업데이트하여 내일까지 다시 공지드릴예정입니다.

**Comment by realcom** [comment]
:GET /rooms/:room_id 로 request보내시면 해당 채팅방에 조인한 유저리스트를 받아올 수 있습니다.
