### ISSUE TITLE
안녕하세요! 과제 관련 문의드립니다.

### ISSUE THREAD

**Issue by hadamjoo** [snuwebprogramming/snu-chat#3]
1. etl 제출함에 6월 10일 00:00분으로 되어있던데 이는 관련 없는 것인가요??

2. 혹시 저번 주 강의영상을 업로드 해주실 수 있으신가요??

**Comment by realcom** [comment]
1. 6.14일로 연장해두겠습니다.
2.네 .

**Comment by realcom** [comment]
2. 올렸습니다.
