### ISSUE TITLE
안녕하세요! 과제2 로그아웃 관련해서 질문드립니다!

### ISSUE THREAD

**Issue by vhehfhvl** [snuwebprogramming/snu-chat#5]
안녕하세요 웹프를 수강하고 있는 김우영이라고 합니다!

1. 새로 업데이트된 ReadMe를 읽어보니 로그인을 할 때 화면 로딩이 완료되고 localStorage에 key가 저장돼있을 시 login으로 키가 valid한지 확인하라고 돼있는데 혹시 그러면 로그아웃할 때 name만 없애고 localStorage에서 key값은 클리어하지 말라는 의미인가요?(만약 key까지 클리어 한다면 key를 따로 적어놓은다음에 localStorage에 임의로 넣지 않는 이상 사실상 login기능이 무용지물이 될 것 같아서요!)
왠지 로그아웃이라는 의미를 생각했을 때 다 클리어해야할 것 같긴한데 다 클리어하는 순간 login 기능이 사실상 없어질 것 같아서 질문드립니다ㅠㅜ

**Comment by realcom** [comment]
key를 클리어 하시고, 통상적인 login 기능은 따로 구현하지 않으시면 됩니다.
